# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmRjZjI4ODBiZGRhMTJiYzYwMTllZDQzYmY1ZWRlNmQ1MmFiZWQzOWMzMDgxYzNjNjZjYzFlNmNjMGU2NGRjZDZjM2U0NDA0ZTgzMGYxZGM3ZDZkMmE1MDcwNTQwODQzYmExMTU5MTdjNmQzNjkyMDVkNWU5NmIzZWQxMTMyMjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
